### ISSUE TITLE
Design questions

### ISSUE THREAD

**Issue by Finfalter** [DataEngineeringLabs/orc-format#8]
I wonder about the rationale of this project:

- would it have been an option to make this functionality part of [arrow2](https://github.com/jorgecarleitao/arrow2)?
- alternatively, would it have been an option to wrap [Apache ORC's C++](https://arrow.apache.org/docs/status.html) implementation in order to make it available in Rust?

Thank you very much for sharing your opinion on this.

**Comment by jorgecarleitao** [comment]
Hey. Thanks for the question! This is already part of arrow2 - check this example: https://github.com/jorgecarleitao/arrow2/blob/main/examples/orc_read.rs

**Comment by Finfalter** [comment]
Sorry, I have missed that part in arrow2 then. That is great!
